config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users do
  	resources :posts, only: :index
  end

  resources :posts

  resources :sessions, only: [:new, :create, :destroy]
  get '/signin',		to: 'sessions#new'
  delete '/signout',	to: 'sessions#destroy'
  get '/signup',		to: 'users#new'

  root to: 'static_pages#home'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  validates :user, presence: true
  validates :title, presence: true,
  			length: {minimum: 6}, 
  			uniqueness: { case_sensitive: false } 
  validates :content, presence: true, 
  			length: {minimum: 6}
end

app/models/user.rb
class User < ApplicationRecord
	has_many :posts
	has_secure_password
	validates :name, presence: true, length: {maximum: 50}
	validates :password, length: {minimum: 6}
	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
	validates 	:email, presence: true, 
				format: { with: VALID_EMAIL_REGEX }, 
				uniqueness: { case_sensitive: false } 

	def User.encrypt(token)
		Digest::SHA1.hexdigest(token)
	end

	def User.new_remember_token
		SecureRandom.urlsafe_base64
	end

	private
	def create_remember_token
		self.remember_token = User.encrypt(User.new_remember_token)
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
	include SessionsHelper
	
	before_action :set_user, only: [:new, :create]

	def index
		@posts = Post.all
	end

	def new
		@post = Post.new
	end

	def show
		@post = Post.find(params[:id])
	end

	def create
		@post = Post.new(ext_post_params)
		if @post.save
			flash[:success] = "Успех!"
			redirect_to @post
		else
			flash.now[:error] = "Введите корректные данные!"
			render 'new'
		end
	end

	private
	def post_params
		params.require(:post).permit(:title, :content)
	end

	def ext_post_params
		ppr = post_params
		ppr[:user] = current_user
		ppr
	end

	def set_user
		unless signed_in?
			flash[:error] = "Войдите, чтобы создавать посты!"
			redirect_to root_path
		end
	end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
	include SessionsHelper

	def new
	end

	def create
		user = User.find_by_email(session_params[:email])
		if user && user.authenticate(session_params[:password])
			sign_in user
			redirect_to user
		else
			flash.now[:error] = "Введите корректные данные!"
			render 'new'
		end
	end

	def destroy
		sign_out current_user
		redirect_to root_url
	end

	private
	def session_params
		params.require(:session).permit(:email, :password)
	end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
	def home

	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
#	before_action :signed_in_user, only: :index

	def index
		@users = User.all
	end

	def show
		@user = User.find(params[:id])
	end

	def new
		@user = User.new
	end

	def create
		@user = User.new(user_params)
		if @user.save
			flash[:success] = "Добро пожаловать!"
			redirect_to @user
		else
			flash.now[:error] = "Введите корректные данные!"
			render :new
		end
	end

	private
	def user_params
		params.require(:user).permit(:name, :email, :password, :password_confirmation)
	end

#	def signed_in_user
#		unless signed_in?
#			flash[:error] = "Зарегистрируйтесь или войдите!"
#			redirect_to signin_url
#		end
#	end

	def correct_user
      	@user = User.find(params[:id])
      	redirect_to(root_url) unless current_user?(@user)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

	def sign_in user
		remember_token = User.new_remember_token
		cookies.permanent[:remember_token] = remember_token
		user.update_attribute(:remember_token, User.encrypt(remember_token))
		self.current_user = user
	end

	def sign_out user
		remember_token = User.new_remember_token
		user.update_attribute(:remember_token, User.encrypt(remember_token))
		cookies.delete(:remember_token)
		self.current_user = nil
	end

	def current_user=(user)
		@current_user = user
	end

	def current_user
		remember_token = 0
		if cookies[:remember_token]
			remember_token = User.encrypt(cookies[:remember_token])
		end
		@current_user ||= User.find_by(remember_token: remember_token)
	end

	def signed_in?
		!current_user.nil?
	end

	def current_user? user
		user == current_user
	end

end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MembersOnly</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <header style="width: 100%; display: block; height: 50px; border: 1px solid blue;">
  	<div style="float: right; color: blue;">
    
      <%= link_to "Posts", posts_path %>
      <% if signed_in? %>
        <%= current_user.name %>
        <%= link_to "Sign out", signout_path, method: "delete" %>
        <%= link_to "Create new post", new_post_path %>
      <% else %>
        <%= link_to "Sign in",  signin_path  %>
        <%= link_to "Sign up",  signup_path  %>
      <% end %>
  	</div>
  </header>
    <%= yield %>
  </body>
</html>

app/views/posts/_new_post_form.html.erb
<%= form_for @post do |f| %>
	<%= f.label "Title" %>
	<%= f.text_field :title %><br>
	<%= f.label "Content" %>
	<%= f.text_area :content %><br>
	<%= f.submit "Create" %>
<% end %>

app/views/posts/index.html.erb
<ul>
	<% @posts.each do |post| %>
		<li>
			<b><%= link_to post.title, post %></b><br>
			<%= post.content[0..30] %>...
		</li>
		<% end %>
</ul>

app/views/posts/new.html.erb
<h1>Creating new user:</h1>
<%= render 'new_post_form' %>

app/views/posts/show.html.erb
<h1><%= @post.title %></h1>
<% if signed_in? %>
	<h6>by <%= @post.user.name %></h6>
<% end %>
<%= @post.content %>

app/views/static_pages/home.html.erb
<h1>Welcome</h1>
<h3>to Members-only homepage</h3>

app/views/users/_reg_form.html.erb
<%= form_for @user do |f| %>
	<%= f.label "Username" %>
	<%= f.text_field :name %><br>
	<%= f.label "e-mail" %>
	<%= f.text_field :email %><br>
	<%= f.label "Password" %>
	<%= f.password_field :password %><br>
	<%= f.label "Confirm your password" %>
	<%= f.password_field :password_confirmation %><br>
	<%= f.submit "Create" %>
<% end %>

app/views/users/index.html.erb
<ul>
	<% @users.each do |user| %>
	<li><%= user.name %></li>
	<% end %>
</ul>

app/views/users/new.html.erb
<h1>Creating new user:</h1>
<%= render 'reg_form' %>
	

app/views/users/show.html.erb
<h1>Here is <%= @user.name.capitalize %>'s page!</h1>